### ISSUE TITLE
My pull request did not perform the test

### ISSUE THREAD

**Issue by gu4d4D3v** [LaravelDaily/Test-Laravel-Routes#1603]
Hello, 

I followed the steps in the video to do the fork and then the merge request but when I did the merger request [1599](https://github.com/LaravelDaily/Test-Laravel-Routes/pull/1599) , the action of running the tests did not execute. Could you help me? 

Thanks

**Comment by gu4d4D3v** [comment]
hey @LaravelDaily, could you help me with my issue?

**Comment by PovilasKorop** [comment]
@gu4d4D3v I've clicked "Approve and run" from our side. Hope that helps!

**Comment by gu4d4D3v** [comment]
yes it helped, I appreciate it very much!
