### ISSUE TITLE
Minor issue.

### ISSUE THREAD

**Issue by akhilkharva** [LaravelDaily/Test-Laravel-Routes#187]
@PovilasKorop , i have found one issue, its a minor but i think it will create issue on system like Linux.

![image](https://user-images.githubusercontent.com/51924462/142366696-795edffd-67e4-4293-9b02-fbcd55d88c14.png)

The directory name V1 is in caps while in route instructions it is in small case.

**Comment by PovilasKorop** [comment]
@akhilkharva in parameters of routes, you can provide both URL prefix and folder/namespace, which can be absolutely different, not only uppercase
