### ISSUE TITLE
Exception "Route [dashboard] not defined" throws

### ISSUE THREAD

**Issue by XristosD** [LaravelDaily/Test-Laravel-Routes#188]
I am facing bellow exception when trying to reach about page although route  has been set correctly : 

Route [dashboard] not defined. (View: /home/xristos/tutorials/laravel-daily/test-your-skills/Test-Laravel-Routes/resources/views/layouts/navigation.blade.php)

When does Route [dashboard]  should be installed? Is it a Breeze route maybe ?
I tried to install Breeze at beginning but it overwrites web.php files

**Comment by Simon-OlivierDesautels** [comment]
How did you fix it? @XristosD

**Comment by danord24** [comment]
Hey, I just added the following just above the `require __DIR__.'/auth.php';` line.

```
Route::get('/dashboard', function () {
    //
})->name('dashboard');
```

It's not part of the test, but half of your tests fail without the named dashboard route. So may aswell add it in!
