### ISSUE TITLE
Why is my Task 3 not working

### ISSUE THREAD

**Issue by emmanuelcoker** [LaravelDaily/Test-Laravel-Routes#627]
![sniping error](https://user-images.githubusercontent.com/56352386/183674733-6e991a76-67cf-4ec2-a114-590e5a4b2ab2.PNG)
I am getting an error saying that this response is not a view

**Comment by emmanuelcoker** [comment]
Works now i have completed my tasks, i continued other tasks and it worked
![sniping success](https://user-images.githubusercontent.com/56352386/183683120-abda6521-031e-4ad9-be0d-9a3437c7ea79.PNG)

**Comment by orsisam** [comment]
I face same problem with you, can You tell me how to fix it?
