### ISSUE TITLE
Potential spelling mistake

### ISSUE THREAD

**Issue by JustinByrne** [LaravelDaily/Test-Laravel-Routes#95]
Looking through the routes/web.php file on the `line 66` it shows `/app` however I believe that this should be `/admin`

https://github.com/LaravelDaily/Test-Laravel-Routes/blob/b6f541e6aabded9989fa467fe6d165a57aa834d7/routes/web.php#L60-L66

I would put in a PR to change this, however I have already created one for the challenge in hand.

**Comment by SunilYadav1961** [comment]
Exactly @JustinByrne 
I think it should be `/admin` instead of `/app`
